# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(911, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 90, 340, 490))
        self.label.setStyleSheet("border-image: url(:/images/images/background.jpeg);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 90, 421, 490))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(520, 170, 208, 46))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_landing = QtWidgets.QPushButton(self.widget)
        self.pushButton_landing.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_landing.setFont(font)
        self.pushButton_landing.setStyleSheet("#pushButton_landing{\n"
"    border:none;\n"
"    color: black;\n"
"}\n"
"#pushButton_landing:focus{\n"
"    \n"
"}")
        self.pushButton_landing.setObjectName("pushButton_landing")
        self.horizontalLayout.addWidget(self.pushButton_landing)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton_enroll = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_enroll.setFont(font)
        self.pushButton_enroll.setStyleSheet("#pushButton_enroll{\n"
"    border:none;\n"
"    color: rgb(186, 186, 186);\n"
"}\n"
"#pushButton_enroll:focus{\n"
"    \n"
"}")
        self.pushButton_enroll.setObjectName("pushButton_enroll")
        self.horizontalLayout.addWidget(self.pushButton_enroll)
        self.widget_landing = QtWidgets.QWidget(self.centralwidget)
        self.widget_landing.setGeometry(QtCore.QRect(440, 220, 381, 341))
        self.widget_landing.setObjectName("widget_landing")
        self.lineEdit_login_account = QtWidgets.QLineEdit(self.widget_landing)
        self.lineEdit_login_account.setGeometry(QtCore.QRect(20, 50, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_login_account.setFont(font)
        self.lineEdit_login_account.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_login_account.setObjectName("lineEdit_login_account")
        self.lineEdit_login_password = QtWidgets.QLineEdit(self.widget_landing)
        self.lineEdit_login_password.setGeometry(QtCore.QRect(20, 140, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_login_password.setFont(font)
        self.lineEdit_login_password.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_login_password.setObjectName("lineEdit_login_password")
        self.pushButton_login = QtWidgets.QPushButton(self.widget_landing)
        self.pushButton_login.setGeometry(QtCore.QRect(20, 260, 341, 51))
        self.pushButton_login.setStyleSheet("#pushButton_login{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_login:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#pushButton_login:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.checkBox_rememberPassword = QtWidgets.QCheckBox(self.widget_landing)
        self.checkBox_rememberPassword.setGeometry(QtCore.QRect(30, 220, 88, 19))
        self.checkBox_rememberPassword.setObjectName("checkBox_rememberPassword")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 110, 41, 31))
        self.pushButton_2.setStyleSheet("border:none;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_enroll = QtWidgets.QWidget(self.centralwidget)
        self.widget_enroll.setGeometry(QtCore.QRect(440, 220, 381, 341))
        self.widget_enroll.setObjectName("widget_enroll")
        self.lineEdit_register_account = QtWidgets.QLineEdit(self.widget_enroll)
        self.lineEdit_register_account.setGeometry(QtCore.QRect(20, 20, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_register_account.setFont(font)
        self.lineEdit_register_account.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_register_account.setObjectName("lineEdit_register_account")
        self.lineEdit_register_password = QtWidgets.QLineEdit(self.widget_enroll)
        self.lineEdit_register_password.setGeometry(QtCore.QRect(20, 100, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_register_password.setFont(font)
        self.lineEdit_register_password.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_register_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_register_password.setObjectName("lineEdit_register_password")
        self.lineEdit_register_passwordConfirm = QtWidgets.QLineEdit(self.widget_enroll)
        self.lineEdit_register_passwordConfirm.setGeometry(QtCore.QRect(20, 180, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_register_passwordConfirm.setFont(font)
        self.lineEdit_register_passwordConfirm.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_register_passwordConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_register_passwordConfirm.setObjectName("lineEdit_register_passwordConfirm")
        self.pushButton_register = QtWidgets.QPushButton(self.widget_enroll)
        self.pushButton_register.setGeometry(QtCore.QRect(20, 260, 341, 51))
        self.pushButton_register.setStyleSheet("#pushButton_register{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_register:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#pushButton_register:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_register.setObjectName("pushButton_register")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_landing.setText(_translate("MainWindow", "登陆"))
        self.pushButton_enroll.setText(_translate("MainWindow", "注册"))
        self.lineEdit_login_account.setPlaceholderText(_translate("MainWindow", "账号："))
        self.lineEdit_login_password.setPlaceholderText(_translate("MainWindow", "密码："))
        self.pushButton_login.setText(_translate("MainWindow", "登陆"))
        self.checkBox_rememberPassword.setText(_translate("MainWindow", "记住密码"))
        self.lineEdit_register_account.setPlaceholderText(_translate("MainWindow", "输入账号："))
        self.lineEdit_register_password.setPlaceholderText(_translate("MainWindow", "设置密码："))
        self.lineEdit_register_passwordConfirm.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.pushButton_register.setText(_translate("MainWindow", "注册"))
import resource_rc
