# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_verify.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 90, 761, 490))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 110, 41, 31))
        self.pushButton_2.setStyleSheet("border:none;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 340, 490))
        self.label_2.setStyleSheet("border-image: url(:/images/images/background.jpeg);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(520, 170, 208, 46))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_verify_label = QtWidgets.QPushButton(self.widget)
        self.pushButton_verify_label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_verify_label.setFont(font)
        self.pushButton_verify_label.setStyleSheet("#pushButton_verify_label{\n"
"    border:none;\n"
"    color: black;\n"
"}\n"
"#pushButton_landing:focus{\n"
"    \n"
"}")
        self.pushButton_verify_label.setObjectName("pushButton_verify_label")
        self.horizontalLayout.addWidget(self.pushButton_verify_label)
        self.widget_enroll = QtWidgets.QWidget(self.centralwidget)
        self.widget_enroll.setGeometry(QtCore.QRect(440, 220, 381, 341))
        self.widget_enroll.setObjectName("widget_enroll")
        self.lineEdit_verify_answer = QtWidgets.QLineEdit(self.widget_enroll)
        self.lineEdit_verify_answer.setGeometry(QtCore.QRect(20, 180, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_verify_answer.setFont(font)
        self.lineEdit_verify_answer.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_verify_answer.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_verify_answer.setObjectName("lineEdit_verify_answer")
        self.pushButton_verify = QtWidgets.QPushButton(self.widget_enroll)
        self.pushButton_verify.setGeometry(QtCore.QRect(20, 260, 341, 51))
        self.pushButton_verify.setStyleSheet("#pushButton_verify{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_verify:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#pushButton_verify:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_verify.setObjectName("pushButton_verify")
        self.pushButton_play_pause = QtWidgets.QPushButton(self.widget_enroll)
        self.pushButton_play_pause.setGeometry(QtCore.QRect(263, 130, 31, 31))
        self.pushButton_play_pause.setStyleSheet("")
        self.pushButton_play_pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play_pause.setIcon(icon1)
        self.pushButton_play_pause.setObjectName("pushButton_play_pause")
        self.label_time = QtWidgets.QLabel(self.widget_enroll)
        self.label_time.setGeometry(QtCore.QRect(320, 80, 41, 31))
        self.label_time.setObjectName("label_time")
        self.label_question = QtWidgets.QLabel(self.widget_enroll)
        self.label_question.setGeometry(QtCore.QRect(20, 20, 291, 41))
        self.label_question.setObjectName("label_question")
        self.pushButton_questionChange = QtWidgets.QPushButton(self.widget_enroll)
        self.pushButton_questionChange.setGeometry(QtCore.QRect(325, 25, 31, 31))
        self.pushButton_questionChange.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/question_change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_questionChange.setIcon(icon2)
        self.pushButton_questionChange.setObjectName("pushButton_questionChange")
        self.horizontalSlider_progress = QtWidgets.QSlider(self.widget_enroll)
        self.horizontalSlider_progress.setGeometry(QtCore.QRect(20, 80, 271, 31))
        self.horizontalSlider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_progress.setObjectName("horizontalSlider_progress")
        self.pushButton_musicChange = QtWidgets.QPushButton(self.widget_enroll)
        self.pushButton_musicChange.setGeometry(QtCore.QRect(325, 130, 31, 31))
        self.pushButton_musicChange.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/music_change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_musicChange.setIcon(icon3)
        self.pushButton_musicChange.setObjectName("pushButton_musicChange")
        self.horizontalSlider_volume = QtWidgets.QSlider(self.widget_enroll)
        self.horizontalSlider_volume.setGeometry(QtCore.QRect(20, 130, 160, 31))
        self.horizontalSlider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_volume.setObjectName("horizontalSlider_volume")
        self.pushButton_sound = QtWidgets.QPushButton(self.widget_enroll)
        self.pushButton_sound.setGeometry(QtCore.QRect(201, 130, 31, 31))
        self.pushButton_sound.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/sound_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sound.setIcon(icon4)
        self.pushButton_sound.setObjectName("pushButton_sound")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_verify_label.setText(_translate("MainWindow", "验证"))
        self.lineEdit_verify_answer.setPlaceholderText(_translate("MainWindow", "输入验证答案："))
        self.pushButton_verify.setText(_translate("MainWindow", "验证"))
        self.label_time.setText(_translate("MainWindow", "--/--"))
        self.label_question.setText(_translate("MainWindow", "问题："))
import resource_rc
